### ISSUE TITLE
name 'img' is not defined

### ISSUE THREAD

**Issue by alisolanki** [mlmed/covid-severity#1]
**CLI Code**

`python predict_severity.py examples/1.jpeg -saliency_path examples/1-heatmap.jpeg`

**Error:**
```
geographic_extent (0-8): 1.208
opacity (0-6): 1.164
Traceback (most recent call last):
  File "predict_severity.py", line 117, in <module>
    img = img.requires_grad_()
NameError: name 'img' is not defined
```

**Comment by ieee8023** [comment]
I pushed a new version of the code that should fix that bug. Thanks for raising the issue!

**Comment by ieee8023** [comment]
Is the issue resolved?

**Comment by alisolanki** [comment]
Checked it. Works now!
